apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slogin.fullname" . }}
  labels:
    {{- include "slogin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "slogin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "slogin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "slogin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: secretKey
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: databaseUrl
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: redisUrl
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: slogin-config
                  key: host
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: slogin-config
                  key: port
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: slogin-config
                  key: logLevel
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: slogin-config
                  key: rustLog
            - name: actix_web
              valueFrom:
                configMapKeyRef:
                  name: slogin-config
                  key: actixWeb
            - name: actix_server
              valueFrom:
                configMapKeyRef:
                  name: slogin-config
                  key: actixServer
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
