apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-out
data:
  fluentd.conf: |
    # TCP input to receive logs from the forwarders
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

    <source>
      @type tail
      path /var/log/containers/slogin*.log
      pos_file /opt/bitnami/fluentd/logs/buffers/fluentd-docker.pos
      tag slogin.*
      read_from_head true
      follow_inodes true
      <parse>
        @type none
      </parse>
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    # Send the logs to the standard output
    <match **>
      @type elasticsearch
      include_tag_key true
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      logstash_format true

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>

# <parse>
#   @type regexp
#   expression /^[^\[]]+\[(?<logtime>\S+)\s+(?<Level>\S+)\s+(?<source>[^\]]+)\]\s+(?<message>.*$)/m
#   time_key logtime
#   time_format %Y-%m-%dT%H:%M:%SZ
# </parse>
