name: docker
on:
  push:
    tags:
      - v*.*.*

jobs:
  image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: docker hub authentication
        uses: docker/login-action@v1
        with:
          username: ilmannafian
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'
      - name: build and push versioned image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          cache-from: figtive/slogin:latest
          tags: |
            ilmannafian/slogin:latest
            ilmannafian/slogin:${{ steps.semver_parser.outputs.major }}
            ilmannafian/slogin:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            ilmannafian/slogin:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
