name: docker
on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    uses: ilmannafian04/dot-github/.github/workflows/docker.yml@main
    with:
      username: ilmannafian
      repository: ilmannafian
      app-name: slogin
    secrets:
      docker-hub-access-token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
